### ISSUE TITLE
hard coded csv file name in pre_process needs to be changed

### ISSUE THREAD

**Issue by varshamadapoosi** [ALTEMIS-DOE/climate-resilience#2]
in this line (https://github.com/satyarth934/lbnl-climate-resilience/blob/4229081432aa779228206c4891125548a278727e/src/climate_resilience/preprocess.py#L95), the calculate_Nth_percentile function seems to hardcode the output as LM_Sites_99th_percentile and needs to be changed depending on the type of sites (EM)

**Comment by satyarth934** [comment]
That was the input data directory path in the `preprocess_example.py` file that was causing the issue.
I have changed that to user input so it should be fine now.
