### ISSUE TITLE
Adjust for loop order - improve download performance

### ISSUE THREAD

**Issue by zexuanxu** [ALTEMIS-DOE/climate-resilience#7]
I'm thinking about the slow download bottleneck we are experiencing

https://github.com/ALTEMIS-DOE/climate-resilience/blob/6014e450ea59a6336604172c24ae050b32ae3ab0/src/climate_resilience/downloader.py#L364

For now, we did something like (pseudo code )
for each site:
    for each variable: 
        for each scenario:
            for each model:

Considering that the most time-consuming part is maybe the loading the raster images on GEE, 
Maybe, this will improve the performance
for each variable: 
    for each scenario:
         for each model:
             for each site:   --> then we do not need to reload the images once again for another site

What do you think?

**Comment by satyarth934** [comment]
- [ ] Try batch download for multiple geometry points.
- [ ] Repeat the error in parallel code.

**Comment by satyarth934** [comment]
This process turns out to be slow in general. 
Downloading from here is not the best idea. 
If the files are dataset specific, it is best to download from alternate sources like AWS or some other NASA servers.
This can be looked at later.
